spring:
  application:
    name: hello-kotlin

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000


  h2:
    console:
      enabled: true
      path: /h2-console

