spring:
  application:
    name: passive-income-app-kis


kis:
  url: https://openapi.koreainvestment.com:9443
  access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0b2tlbiIsImF1ZCI6IjFiMjEyNTAxLWNkNDMtNDljNS1iMjlmLWE4ODc5NWFjMzVkNCIsInByZHRfY2QiOiIiLCJpc3MiOiJ1bm9ndyIsImV4cCI6MTczMzIxNzQ5NywiaWF0IjoxNzMzMTMxMDk3LCJqdGkiOiJQU2p5RUZiWVRuZW9oRjVNdWRyemJoWThnVmNFQTM1dm5FOXIifQ.4RFQOgu_av86NkNev4GKjN3OLvCMY781ggmOCXfgm3kQSH7Y_ldHUWbasnUUjWsKRknWWRZ254j98LAx49651g
  app-key: PSjyEFbYTneohF5MudrzbhY8gVcEA35vnE9r
  app-secret: jCVDFhKuIZWh2n8vzyO1gqePaaayjpWsGWfpY/Y3lrf+mwU1wEkbLjzcs24L4YgE/agJMGSLt6YyJCqxnaW4A2QtFhDCXKVEz9i27PW7yECzs56tHBLqGuZOdeH+7YC6PtZb7uHdtkRRbyzrJmKya/1qPELY+E+WiDjRVCZuTS1DJXwjQAE=
