package org.mj.passiveincome.app.api.config.security.oauth2

object OAuth2ParameterNames {
  const val GRANT_TYPE = "grant_type"
  const val RESPONSE_TYPE = "response_type"
  const val CLIENT_ID = "client_id"
  const val CLIENT_SECRET = "client_secret"
  const val CLIENT_ASSERTION_TYPE = "client_assertion_type"
  const val CLIENT_ASSERTION = "client_assertion"
  const val ASSERTION = "assertion"
  const val REDIRECT_URI = "redirect_uri"
  const val SCOPE = "scope"
  const val STATE = "state"
  const val CODE = "code"
  const val ACCESS_TOKEN = "access_token"
  const val TOKEN_TYPE = "token_type"
  const val EXPIRES_IN = "expires_in"
  const val REFRESH_TOKEN = "refresh_token"
  const val USERNAME = "username"
  const val PASSWORD = "password"
  const val ERROR = "error"
  const val ERROR_DESCRIPTION = "error_description"
  const val ERROR_URI = "error_uri"
  const val REGISTRATION_ID = "registration_id"
  const val TOKEN = "token"
  const val TOKEN_TYPE_HINT = "token_type_hint"
  const val DEVICE_CODE = "device_code"
  const val USER_CODE = "user_code"
  const val VERIFICATION_URI = "verification_uri"
  const val VERIFICATION_URI_COMPLETE = "verification_uri_complete"
  const val INTERVAL = "interval"
  const val AUDIENCE = "audience"
  const val RESOURCE = "resource"
  const val REQUESTED_TOKEN_TYPE = "requested_token_type"
  const val ISSUED_TOKEN_TYPE = "issued_token_type"
  const val SUBJECT_TOKEN = "subject_token"
  const val SUBJECT_TOKEN_TYPE = "subject_token_type"
  const val ACTOR_TOKEN = "actor_token"
  const val ACTOR_TOKEN_TYPE = "actor_token_type"
}
