spring:
  application:
    name: passive-income-app-service
  profiles:
    active: local, oauth2

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

  data:
    redis:
      repositories:
        enabled: false

logging:
  level:
    root: info

app:
  security:
    filter-chain: oauth2
    jwt:
      access-token:
        secret: ${JWT_ACCESS_TOKEN_SECRET}
        expiration: PT24H
    oauth2:
      provider:
        google:
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}
          redirect-uri: http://localhost:3000/oauth2/code/google
          scope:
            - email
            - profile

