spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Dev/h2/databases/passive-income-test;MODE=PostgreSQL
    username: sa

  jpa:
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    redis:
      host: localhost
      port: 6379

app:
  security:
    create-test-user: true
