spring:
  application:
    name: passive-income-app-service
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

logging:
  level:
    root: info

