spring:
  application:
    name: passive-income-app-service
  profiles:
    active: local, oauth

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

  data:
    redis:
      repositories:
        enabled: false

logging:
  level:
    root: info

app:
  security:
    filter-chain: oauth
